repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: false
        types: [python]
        args: ['--line-length', '80', '.']

      - id: isort
        name: isort
        entry: isort
        language: system
        pass_filenames: false
        types: [python]

#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]

#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        pass_filenames: false
#        types: [python]

